spring.application.name=spring-security-jwt
spring.profiles.active=local

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
# Hex encoded 256-bit HMAC key
security.jwt.secret-key=3cfa76f114ea762bc1050e685f02d4e8c1ea9c4266f8e7b1a20bf77a06c8b939
# 1 hour (3,600,000 milliseconds)
security.jwt.expiration-time=3600000
# 7 days (604,800,000 milliseconds)
security.jwt.refresh-expiration-time=604800000

