# Database Configuration for Local Environment
spring.datasource.url=jdbc:mysql://localhost:3306/jwt_tct?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Virendra@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server Port
server.port=8080
